config/routes.rb
Rails.application.routes.draw do

  #get 'categories/index'
  #get 'categories/show'
  #get 'categories/update'
  #get 'categories/destroy'
  #get 'categories/new'
  #get 'categories/edit'
  #get 'posts/index'

  root to: 'home#home', as: 'home'
  resources :posts
  resources :categories
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to category_path(@category.id)
  end

  def edit
    @category = Category.find(params[:id])
  end


  private

  def category_params
    params.require(:category).permit(:name, :slug)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path

  end





  private

  def post_params
    params.require(:post).permit(:name, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/create.html.erb
<h1>Creation d'une catégorie</h1>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Modifier la catégorie</h1>

<%= form_for @category do |f| %>

    <div class="form-group">
        <%= f.text_field :name, placeholder: 'Nom de la catégorie', class: 'form-control'%>      
    </div>

    <div class="form-group">
        <%= f.text_field :slug, placeholder: 'url de la catégorie', class: 'form-control'%>      
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Modifier</button>
    </div>


<% end %>

app/views/categories/index.html.erb
<h1>Les catégories</h1>

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Nom catégorie</td>
            <td>Action</td>
        
        </tr>
    
    </thead>


    <tbody>
    
        <% @categories.each do |category| %>
            <tr>
                <td><%=  category.id %></td>
                <td><%=  category.name %></td>
                <td>
                    <a href="<%= edit_category_path(category.id) %>" class="btn btn-primary">Editer</a>
                    <a href="<%= category_path(category.id) %>" class="btn btn-secondary">Details</a>
                    <a href="<%= category_path(category.id) %>" class="btn btn-danger" data-confirm="t'es sur de toi?" data-method="DELETE">Supprimer</a>
                </td>
            </tr>


        <% end %>
    
    </tbody>

</table>

<p>
    <a href="<%= new_category_path %>" class="btn btn-success">Créer une nouvelle catégorie</a>

</p>

app/views/categories/new.html.erb
<h1>Nouvelle catégorie</h1>

<%= form_for @category do |f| %>

    <div class="form-group">
        <%= f.text_field :name, placeholder: 'Nom de la catégorie', class: 'form-control'%>      
    </div>

    <div class="form-group">
        <%= f.text_field :slug, placeholder: 'url de la catégorie', class: 'form-control'%>      
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Créer</button>
    </div>


<% end %>

app/views/categories/show.html.erb
<h1>Détails de la catégorie: <%= @category.name %>  </h1>
<p><%= @category.slug %></p>
<p>
    <a href="<%= posts_path %> " class="btn btn-info" >Revenir aux listes des catégories</a>
</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/home/home.html.erb
<h1>Bienvenue, Page Home</h1>

<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis fugiat autem odit doloremque iste cumque id adipisci? Mollitia laborum earum, commodi expedita soluta facilis molestias error quo, cumque saepe eligendi!
Distinctio illum repellendus culpa, similique maxime velit possimus voluptatem ducimus necessitatibus esse corrupti assumenda tempore consectetur id suscipit nemo pariatur nulla rerum obcaecati facilis, cupiditate ab. Cupiditate ut officia reprehenderit!
Ipsum atque facilis voluptatum rerum corporis! Odio consequuntur quia, possimus, aperiam commodi corporis, magnam a nam eligendi similique sapiente. Quod illo, assumenda vitae doloremque similique dicta ex dolor impedit cum!
</p>

<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores beatae molestias cum eos officia quam provident repudiandae sapiente, qui, laudantium, nihil explicabo quasi nam atque quidem! In sit reprehenderit quia!Accusantium nulla maxime expedita possimus quis, repellendus, autem animi enim incidunt debitis dolorem repellat. Beatae dignissimos totam accusamus, quam voluptatibus cum ducimus ipsam commodi, facere consequuntur doloremque tenetur a sed!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grafikart2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand" href="<%= home_path %>">Tuto ruby on rails</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item ">
            <a class="nav-link" href="<%= home_path %>">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">Articles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= categories_path %>">Categorie</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editer l'article : <%= @post.name %> </h1>

<%= form_for @post do |f| %>

    <div class="form-group">
        <label> Titre de l'article </label>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <label>Contenu de l'article</label>
        <%= f.text_area :contect, class: 'form-control' %>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-secondary">Modifier l'article</button>
    </div>

<% end %>

app/views/posts/index.html.erb
<h1>Bienvenue, Liste des articles</h1>

<% @posts.each  do |post|%>

    <h2><%= post.name %></h2>

    <p>
        <a href="<%= post_path(post.id) %>" class="btn btn-primary">Lire la suite</a>
        <a href="<%= edit_post_path(post.id) %>" class="btn btn-info" >Editer l'article</a>
        <a href="<%= post_path(post.id) %>" class="btn btn-danger" data-confirm="t'es sure? " data-method="DELETE" >Supprimer</a>
    
    </p>

<% end %>


<p>

    <a href="<%= new_post_path %>" class="btn btn-success">Nouvel Article</a>

</p>

app/views/posts/new.html.erb
<h1>Nouvel Article</h1>

<%= form_for @post do |f| %>

    <div class="form-group">
        <label> Titre de l'article </label>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <label>Contenu de l'article</label>
        <%= f.text_area :contect, class: 'form-control' %>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-secondary">Créer l'article</button>
    </div>

<% end %>

app/views/posts/show.html.erb
<h1>Détails de l'article : <%= @post.name %>  </h1>
<p><%= @post.contect %></p>
<p>
    <a href="<%= posts_path %> " class="btn btn-info" >Revenir aux listes des articles</a>
</p>